version: '3'

services:
    django:
        build: .
        container_name: django_p
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
          - ./:/apps/test_image
        ports:
          - "8000:8000"
        environment:
          - DEBUG=1
          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
          #- CELERY_BROKER=redis://redis:6379/0
          #- CELERY_BACKEND=redis://redis:6379/0
      
        #depends_on:
        #  - redis
      
    #celery-worker:
    #    build: .
    #    command: celery -A apps.teams.taskapp.celery worker -l INFO
    #    volumes:
    #        - ./:/apps/deepsea_test
    #    environment:
    #        - DEBUG=1
    #        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    #        - CELERY_BROKER=redis://redis:6379/0
    #        - CELERY_BACKEND=redis://redis:6379/0
    #    depends_on:
    #        - django
    #        - redis
            
    # celery_beat:

    #redis:
    #    image: redis:3.2
    
   

